FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
RUN echo "- - - ALTAZION BUILD - - -"
COPY program.dll /program.dll
COPY TemplateBuilder.dll /TemplateBuilder.dll
COPY program.runtimeconfig.json /program.runtimeconfig.json
