name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore /home/runner/work/templatebuilder/templatebuilder/src/TemplateBuilder.sln
    - name: Build
      run: dotnet build --configuration Release --output /home/runner/work/templatebuilder/templatebuilder/release/ --no-restore /home/runner/work/templatebuilder/templatebuilder/src/TemplateBuilder.sln
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1      
#    - name: Login to Docker Hub
#      uses: docker/login-action@v1
#      with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#          push: true
#          tags: altazion/template-builder:latest
    - name: Build Image
      run: docker build /home/runner/work/templatebuilder/templatebuilder/release/ --file /home/runner/work/templatebuilder/templatebuilder/release/Dockerfile --tag altazion/template-builder:latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push to Docker Hub
      run: docker push altazion/template-builder:latest
